name: Integration Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
        client: [ JAVA_NET, APACHE_CLIENT_4, APACHE_CLIENT_5 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run created binary
      run: target/radiorecorder-*-bin/radiorecorder-*/bin/radiorecorder.sh -client ${{ matrix.client }} -abort-after 100 deutschlandfunk -d deutschlandfunk
    - name: Output mime type of first mp3
      run: |
        FIRST_MPEG=$(ls deutschlandfunk/*/*.mp3 | head -n1)
        if [ ! -f "${FIRST_MPEG}" ]; then
          echo "Not a file: ${FIRST_MPEG}"
          exit 1
        fi

        FILE_SIZE=$(stat --printf %s ${FIRST_MPEG})
        if [ ${FILE_SIZE} -lt 100000 ]; then
          echo "File ${FIRST_MPEG} is too short: ${FILE_SIZE}"
          exit 2
        else
          echo "File size of ${FIRST_MPEG}: ${FILE_SIZE}"
        fi

        FILE_TYPE="$(file --brief --mime ${FIRST_MPEG})"
        if [ "${FILE_TYPE}" != "audio/mpeg; charset=binary" ]; then
          echo "File type is wrong: $(file --mime $(ls deutschlandfunk/*/*.mp3 | head -n1))"
          exit 3
        else
          echo "File type of ${FIRST_MPEG}: ${FILE_TYPE}"
        fi

