name: Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Extract current maven version
      run: echo "::set-output name=version::$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)"
      id: version
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: binary
        path: target/radiorecorder-${{ steps.version.outputs.version }}-bin.tar.gz
  debian:
    needs: build
    runs-on: ubuntu-latest
    container: debian:10
    env:
      JDK_URL: https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.1%2B9/OpenJDK15U-jdk_x64_linux_hotspot_15.0.1_9.tar.gz
      JAVA_HOME: /usr/lib/jdk
    steps:
      - uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: binary
      - name: Extract build
        run: |
          tar -xzvf radiorecorder-${{ needs.build.outputs.version }}-bin.tar.gz
      - name: Setup container
        run: |
          echo "List of current dir:"
          ls -al
          echo "Debian version:"
          cat /etc/debian_version
          echo "Updating"
          apt-get update
          echo "Installing"
          apt-get install -y --no-install-recommends curl openssh-client git fakeroot curl binutils
          mkdir ${{ env.JAVA_HOME }}
          curl --insecure --location ${{ env.JDK_URL }} --output - | \
          tar -xzf- --strip-components 1 --directory ${{ env.JAVA_HOME }}
          ${{ env.JAVA_HOME }}/bin/jpackage jpackage \
            --name radiorecorder \
            --type deb \
            --app-version ${{ needs.build.outputs.version }} \
            --copyright "Stephan Fuhrmann" \
            --vendor "Stephan Fuhrmann" \
            --description "Records and plays internet radio streams" \
            --license-file LICENSE \
            --main-jar lib/radiorecorder-${{ needs.build.outputs.version }}.jar \
            --main-class de.sfuhrm.radiorecorder.Main \
            --input radiorecorder-${VERSION} \
            --linux-deb-maintainer s@sfuhrm.de \
            --linux-app-category sound \
            --dest jpackage-app \
            --verbose
